name: Deploy to Firebase

on:
  push:
    branches:
      - master
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  MAIN_KEY: ${{ secrets.MAIN_KEY }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_NEW_DEVELOPER_ACCOUNT_TEMPLATE: ${{ secrets.SENDGRID_NEW_DEVELOPER_ACCOUNT_TEMPLATE }}
  GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
  GA_API_SECRET: ${{ secrets.GA_API_SECRET }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  GITHUB_STATS_TOKEN: ${{ secrets.GITHUB_STATS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  NODE_ENV: production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16'
      - name: Install Project Dependencies
        run: |
          rm -rf ./node_modules; yarn install
          npm install -g firebase-tools @babel/core @babel/cli @babel/plugin-transform-react-jsx
          ls ./node_modules/.bin
          pwd
      - name: Install Cloud Dependencies
        run: cd functions; rm -rf ./node_modules/; yarn; cd ..; pwd
      - name: Migrate MongoDB Data
        run: |
          firebase functions:config:set env.redis_status=true runtime.env=production --token $FIREBASE_TOKEN
          pwd
          yarn migrate
      - name: Build Production Project
        run: |
          firebase use default --token $FIREBASE_TOKEN
          firebase functions:config:set runtime.env="production" env.main_key=$MAIN_KEY env.mongo_uri=$MONGO_URI --token $FIREBASE_TOKEN
          firebase functions:config:set env.firebase_config=$FIREBASE_CONFIG --token $FIREBASE_TOKEN
          firebase functions:config:set sendgrid.api_key=$SENDGRID_API_KEY sendgrid.new_developer_account_template=$SENDGRID_NEW_DEVELOPER_ACCOUNT_TEMPLATE --token $FIREBASE_TOKEN
          firebase functions:config:set analytics.ga_tracking_id=$SENDGRID_API_KEY analytics.ga_api_secret=$GA_API_SECRET --token $FIREBASE_TOKEN
          firebase functions:config:set env.redis_url=$REDIS_URL --token $FIREBASE_TOKEN
          firebase functions:config:set aws.access_key=$AWS_ACCESS_KEY_ID aws.secret_access_key=$AWS_SECRET_ACCESS_KEY aws.bucket=$AWS_S3_BUCKET aws.region=$AWS_REGION  --token $FIREBASE_TOKEN
          firebase functions:config:set github.stats_token=$GITHUB_STATS_TOKEN  --token $FIREBASE_TOKEN
          yarn build
      - name: Deploy to prod
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --project=igbo-api-bb22d --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
